services:
    Titi60\SyliusPickupPlugin\Controller\PickupController:
        public: true
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.country"